set_property SRC_FILE_INFO {cfile:{e:/IC/Mark VI/Vivado/CPU/CPU.gen/sources_1/ip/ROM/ROM/ROM_in_context.xdc} rfile:../../../../../CPU.gen/sources_1/ip/ROM/ROM/ROM_in_context.xdc id:1 order:EARLY scoped_inst:InstructionFetchUnit/InstructionMemory} [current_design]
set_property SRC_FILE_INFO {cfile:{e:/IC/Mark VI/Vivado/CPU/CPU.gen/sources_1/ip/RAM/RAM/RAM_in_context.xdc} rfile:../../../../../CPU.gen/sources_1/ip/RAM/RAM/RAM_in_context.xdc id:2 order:EARLY scoped_inst:MemoryAccessUnit/DataMemory} [current_design]
set_property SRC_FILE_INFO {cfile:{E:/IC/Mark VI/constraints/RISCV.xdc} rfile:../../../../../../../constraints/RISCV.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells InstructionFetchUnit/InstructionMemory]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MemoryAccessUnit/DataMemory/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MemoryAccessUnit/DataMemory]
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name CLK [get_ports CLK]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks CLK] -max 0.500 [get_ports RST]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK] -max 0.500 [get_ports {ALUResult[*]}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK] -max 0.500 [get_ports {WriteData[*]}]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK] -max 0.500 [get_ports {PC[*]}]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK] -max 0.500 [get_ports MemWrite]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells InstructionFetchUnit/InstructionMemory]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells MemoryAccessUnit/DataMemory]
